apiVersion: apps/v1
kind: Deployment
metadata:
  name: internship-management-system-api
spec:
  selector:
    matchLabels:
      app: internship-management-system-api
  replicas: 1
  template:
    metadata:
      labels:
        app: internship-management-system-api
    spec:
      containers:
        - name: ims-api
          image: esraekmekci/ims-api:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          resources:
            requests:
              cpu: 200m
              memory: 1Gi
            limits:
              cpu: 1
              memory: 1Gi